name = "numina"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Numina"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.11.0-rc1"

[[lean_lib]]
name = "Numina"
